window.CHARACTERS = {
  earth_berserker_yan: {
    name: "裂地狂战·岩",
    school: "战士 / 重装前排",
    hp: 156,
    speed: 282,
    jump: 610,
    power: 1.18,
    profile: "heavy",
    color: "#c67d42",
    accent: "#f0c16f",
    description: "高承伤前排，依靠减速、护盾和防御姿态稳定压场。",
    skill1: "撼地践踏",
    skill2: "狂怒战意",
    skill3: "不屈堡垒",
    fx: { q: "stomp", e: "rageCone", r: "fortress" },
    jutsu: "狂怒战意",
    ultimate: "不屈堡垒",
  },
  shadow_blade_ye: {
    name: "影刃刺客·夜",
    school: "刺客 / 单体爆发",
    hp: 88,
    speed: 404,
    jump: 760,
    power: 1.14,
    profile: "swift",
    color: "#4f556f",
    accent: "#b784ff",
    description: "瞬移切后排，围绕破绽和隐身打高爆发斩杀。",
    skill1: "暗影步",
    skill2: "致命连击",
    skill3: "遁影无踪",
    fx: { q: "shadowStepStrike", e: "tripleStrike", r: "stealthBurst" },
    jutsu: "致命连击",
    ultimate: "遁影无踪",
  },
  bloodblade_fei: {
    name: "血契剑士·绯",
    school: "战士 / 吸血续航",
    hp: 126,
    speed: 318,
    jump: 668,
    power: 1.08,
    profile: "standard",
    color: "#b83d53",
    accent: "#ff8f8f",
    description: "以生命换爆发，越残越强，依靠吸血和护盾持续作战。",
    skill1: "血刃斩",
    skill2: "痛楚转化",
    skill3: "血之契约",
    fx: { q: "bloodWave", e: "painBurst", r: "bloodPact" },
    jutsu: "痛楚转化",
    ultimate: "血之契约",
  },
  puppet_master_shu: {
    name: "机关傀儡师·枢",
    school: "召唤 / 战术控制",
    hp: 102,
    speed: 338,
    jump: 680,
    power: 1.02,
    profile: "standard",
    color: "#7d6c56",
    accent: "#e0b36d",
    description: "依靠傀儡突进、丝线控制和共鸣强化打节奏压制。",
    skill1: "傀儡突袭",
    skill2: "丝线操控",
    skill3: "傀儡共鸣",
    fx: { q: "puppetRush", e: "silkPull", r: "puppetResonance" },
    jutsu: "丝线操控",
    ultimate: "傀儡共鸣",
  },
  thunder_general_xiao: {
    name: "雷霆战将·霄",
    school: "战士 / 范围控制",
    hp: 132,
    speed: 324,
    jump: 666,
    power: 1.06,
    profile: "standard",
    color: "#4d76c9",
    accent: "#7ae2ff",
    description: "突刺挂感电，雷域控场，再用天罚雷击打爆发。",
    skill1: "雷光突刺",
    skill2: "雷霆领域",
    skill3: "天罚雷击",
    fx: { q: "thunderThrust", e: "thunderField", r: "thunderStrike" },
    jutsu: "雷霆领域",
    ultimate: "天罚雷击",
  },
  frost_mage_lin: {
    name: "霜华魔导·凛",
    school: "法师 / 减速控场",
    hp: 94,
    speed: 306,
    jump: 650,
    power: 1.12,
    profile: "standard",
    color: "#7bd2f6",
    accent: "#e1f6ff",
    description: "减速、冻结、暴风雪处决，擅长站桩控场。",
    skill1: "极寒新星",
    skill2: "冰棱折射",
    skill3: "绝对零度",
    fx: { q: "frostNova", e: "iceShard", r: "absoluteZero" },
    jutsu: "冰棱折射",
    ultimate: "绝对零度",
  },
  star_archer_chen: {
    name: "星轨射手·辰",
    school: "射手 / 远程消耗",
    hp: 92,
    speed: 352,
    jump: 690,
    power: 1.04,
    profile: "swift",
    color: "#5f8fe6",
    accent: "#f4d37f",
    description: "靠远距离连射、陷阱牵引和贯穿全图的大招磨血。",
    skill1: "星矢连射",
    skill2: "引力陷阱",
    skill3: "星轨贯穿",
    fx: { q: "starVolley", e: "gravityTrap", r: "starPierce" },
    jutsu: "引力陷阱",
    ultimate: "星轨贯穿",
  },
  inferno_warlock_jin: {
    name: "炎狱术士·烬",
    school: "法师 / 持续灼烧",
    hp: 96,
    speed: 300,
    jump: 640,
    power: 1.16,
    profile: "standard",
    color: "#cf5e2d",
    accent: "#ffbe55",
    description: "挂灼烧、引爆印记、火海压场，越打越烫。",
    skill1: "烈焰喷吐",
    skill2: "爆燃引爆",
    skill3: "炼狱火海",
    fx: { q: "flameBreath", e: "burnDetonate", r: "infernoSea" },
    jutsu: "爆燃引爆",
    ultimate: "炼狱火海",
  },
  ranger_ling: {
    name: "翠羽游侠·翎",
    school: "射手 / 机动风筝",
    hp: 98,
    speed: 368,
    jump: 724,
    power: 1,
    profile: "swift",
    color: "#57a870",
    accent: "#d3f79b",
    description: "靠位移、陷阱和风筝打法持续牵制对手。",
    skill1: "穿林箭",
    skill2: "藤缚陷阱",
    skill3: "翠羽风暴",
    fx: { q: "forestArrow", e: "vineTrap", r: "featherStorm" },
    jutsu: "藤缚陷阱",
    ultimate: "翠羽风暴",
  },
  thunder_sage_yao: {
    name: "雷霆法尊·曜",
    school: "法师 / 连锁爆发",
    hp: 100,
    speed: 308,
    jump: 650,
    power: 1.18,
    profile: "standard",
    color: "#6d7dff",
    accent: "#82f0ff",
    description: "感电、麻痹、连锁落雷，专精成套爆发。",
    skill1: "闪电链",
    skill2: "静电立场",
    skill3: "天罚雷暴",
    fx: { q: "lightningChain", e: "staticField", r: "thunderStorm" },
    jutsu: "静电立场",
    ultimate: "天罚雷暴",
  },
  night_summoner_yuan: {
    name: "暗夜献祭者·渊",
    school: "召唤 / 持续攻击",
    hp: 108,
    speed: 294,
    jump: 628,
    power: 1.1,
    profile: "standard",
    color: "#463f67",
    accent: "#9b8cff",
    description: "召唤幽灵和魔王，以献祭和中毒压低全场血线。",
    skill1: "幽灵召唤",
    skill2: "怨毒遗骸",
    skill3: "魔王降临",
    fx: { q: "ghostSummon", e: "poisonRemains", r: "demonFall" },
    jutsu: "怨毒遗骸",
    ultimate: "魔王降临",
  },
  moth_hill: {
    name: "逐火之蛾·希尔",
    school: "召唤 / 海量召唤",
    hp: 104,
    speed: 320,
    jump: 660,
    power: 1.06,
    profile: "standard",
    color: "#cf8d66",
    accent: "#ffdfb0",
    description: "用大量召唤物铺场，再通过吞噬和联动制造压制。",
    skill1: "蜉蝣之舞",
    skill2: "饕餮之口",
    skill3: "花蝶幻梦",
    fx: { q: "mayflySwarm", e: "taotieMaw", r: "flowerDream" },
    jutsu: "饕餮之口",
    ultimate: "花蝶幻梦",
  },
};
